name: Deploy to Maven Central

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup maven central
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish
        run: mvn --batch-mode deploy -Pdeploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_NAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_SECRET }}
